version: "3.8"

services:
  bot:
    image: disco_dan:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      FFMPEG_EXECUTABLE: /usr/bin/ffmpeg
      AUDIO_BUFFER_PATH: /tmp
      AUDIO_BUFFER_NAME: now_playing
    depends_on:
      - "db"
    secrets:
      - disco_dan_conn_str
      - test_conn_str
  db:
    image: postgres:13-alpine
    env_file: .env
    environment:
      POSTGRES_DB: disco_dan
      POSTGRES_USER: disco_dan

secrets:
  disco_dan_conn_str:
    file: tmp/disco_dan_conn_str
  test_conn_str:
    file: tmp/test_conn_str