version: "3.8"


services:
  disco_dan:
    image: disco_dan:latest
    restart: unless-stopped
    volumes:
      - type: volume
        source: sqlite
        target: /sqlite
    env_file: .env
    environment: 
      FFMPEG_EXECUTABLE: /usr/bin/ffmpeg
      DISCO_DAN_CONNECTION_STRING: "sqlite:////sqlite/disco_dan/db.sqlite3"
      TEST_CONNECTION_STRING: "sqlite:////sqlite/disco_dan/test_db.sqlite3"
      AUDIO_BUFFER_PATH: /tmp/disco_dan/

volumes:
  sqlite: