""" Project Settings """

import os

from dotenv import load_dotenv

load_dotenv()

AUDIO_BUFFER_PATH = os.getenv("AUDIO_BUFFER_PATH", "buffer")
AUDIO_BUFFER_NAME = os.getenv("AUDIO_BUFFER_NAME", "now_playing.mp4")
FFMPEG_EXECUTABLE = os.getenv("FFMPEG_EXECUTABLE")

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN", "")
DISCORD_GUILD = os.getenv("DISCORD_GUILD")
DISCORD_TEST_GUILD = os.getenv("DISCORD_TEST_GUILD", DISCORD_GUILD)

DISCO_DAN_CONNECTION_STRING = os.getenv("DISCO_DAN_CONNECTION_STRING")
TEST_CONNECTION_STRING = os.getenv("TEST_CONNECTION_STRING")
USE_SEARCH_CACHE = not DISCO_DAN_CONNECTION_STRING is None

DEFAULT_TEXT_CHANNEL = os.getenv("DEFAULT_TEXT_CHANNEL")
DEFAULT_VOICE_CHANNEL = os.getenv("DEFAULT_VOICE_CHANNEL")

YOUTUBE_TOKEN = os.getenv("YOUTUBE_TOKEN")
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"
